### ISSUE TITLE
Erreur au moment de lancer le projet (npm start)

### ISSUE THREAD

**Issue by eslambasher** [salim499/Test_Technique_NodeJs_RestfullApi#1]
Test_Technique_NodeJs_RestfullApi/nodejs_api/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node: undefined symbol: napi_add_finalizer

**Comment by eslambasher** [comment]
Le projet a été lancé sur Ubuntu (Linux)

**Comment by salim499** [comment]
Bonjour,

J'ai vérifié le projet et j'ai pas très bien compris pourquoi il tourne pas
chez vous car chez moi ça tourne très bien.

Je vous ai envoyé une vidéo démonstrative du projet je sais pas si vous
l'avez reçu.

Je vous ai envoyé aussi les deux projets en format zip à télécharger via
deux liens différents.

Sinon vous pouvez m'appeler via le 0 7 64 23 42 94 pour vous expliquer
comment faire fonctionner les deux projets et m'expliquer plus l'erreur.

Bien Cordialement.

Le mar. 8 sept. 2020 à 10:25, Abdulmola Eslam <notifications@github.com> a
écrit :

**Comment by eslambasher** [comment]
Le probleme vient de ma version de node sur la machine, votre projet ne fonctionne qu'a partir de la version 10.

**Comment by salim499** [comment]
D'accord donc là le projet fonctionne très bien après que vous avez changé
la version node?

Je tiens à préciser que les seuls fichiers à voir sont product et user soit
dans routes, controllers et models, j'ai essayé d'ajouter les
commandes(orders) comme bonus mais j'ai pas eu le temps donc dans
l'application react je fait des requêtes que sur product et user.

Cordialement.

Le mar. 8 sept. 2020 à 16:05, Abdulmola Eslam <notifications@github.com> a
écrit :
